import glob

####
# import the environment
####
Import('env build_dir')

####
# build sources
####
srcs = map(lambda x,bd=build_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to ease building it later
####
lib = env.SharedLibrary('%s/PythonInterpreter%s' % (build_dir, env['PYTHONVERSION']),objs)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('PythonInterpreter', libInstall)

####
# return the plug-in library
####
Return("libInstall")
